Repository TencentBlueKing/BKFlow, pull requests merged in 2024-10, with the labels that each got.

#30 fix: 1.8.0验收问题修复 --story=131115465
  bkflow/space/migrations/0007_alter_space_app_code.py
  bkflow/space/models.py
Labels: bugfix

#29 fix: 1.8.0产品验收问题 --story=131115507
  frontend/src/App.vue
  frontend/src/components/layout/NavigationHeadLeft.vue
  frontend/src/config/i18n/cn.js
  frontend/src/config/i18n/en.js
  frontend/src/mixins/tableHeader.js
  frontend/src/scss/common.scss
  frontend/src/views/admin/Space/DecisionTable/index.vue
  frontend/src/views/admin/Space/SpaceConfig/index.vue
  frontend/src/views/admin/Space/Task/index.vue
  frontend/src/views/admin/Space/Template/CreateTaskDialog.vue
  frontend/src/views/admin/Space/Template/CreateTemplateDialog.vue
  frontend/src/views/admin/Space/Template/index.vue
  frontend/src/views/admin/common/SpaceDialog.vue
Labels: bugfix

#32 feat: release 1.8.1 #31
  app_desc.yaml
  scripts/start_new_version.sh
Labels: feature

#34 fix: 日期时间范围变量值类型错误问题修复 #33
  frontend/src/utils/checkDataType.js
Labels: bugfix

#35 fix: 日期时间范围变量值类型错误问题修复 #33
  frontend/src/utils/checkDataType.js
Labels: bugfix

#36 feat: 文档中心跳转支持中英文 --story=132104161
  bkflow/interface/context_processors.py
Labels: feature

#37 chore: 出现全局公告时会额外出一个滚动条问题优化 --story=131115507
  frontend/src/App.vue
Labels: optimization

#38 feat: 调试任务相关交互优化方案 --story=119022030
  frontend/src/components/common/RenderForm/formMixins.js
  frontend/src/config/i18n/cn.js
  frontend/src/config/i18n/en.js
  frontend/src/views/template/TemplateMock/Header.vue
  frontend/src/views/template/TemplateMock/MockExecute/components/DiffDialog.vue
  frontend/src/views/template/TemplateMock/MockExecute/components/MockRecode.vue
  frontend/src/views/template/TemplateMock/MockExecute/index.vue
  frontend/src/views/template/TemplateMock/index.vue
Labels: feature

#43 feat: 接口 get_task_list 支持状态过滤 #41
  bkflow/apigw/views/get_task_list.py
  bkflow/task/views.py
Labels: feature

#45 feat: create_space api 添加 APP 白名单 #44
  bkflow/apigw/views/create_space.py
  config/default.py
  env.py
Labels: feature

#50 feat: http 插件支持 json 转义 #40
  bkflow/pipeline_plugins/components/collections/http/v1_0.py
Labels: feature

#51 feat: release 1.9.0 #31
  app_desc.yaml
  bkflow/apigw/serializers/task.py
  bkflow/apigw/views/create_space.py
  bkflow/apigw/views/create_task_without_template.py
  bkflow/apigw/views/get_task_list.py
  bkflow/interface/context_processors.py
  bkflow/pipeline_plugins/components/collections/http/v1_0.py
  bkflow/pipeline_plugins/query/select.py
  bkflow/pipeline_plugins/static/variables/select.js
  bkflow/space/migrations/0007_alter_space_app_code.py
  bkflow/space/models.py
  bkflow/task/views.py
  config/default.py
  env.py
  frontend/src/App.vue
  frontend/src/components/layout/NavigationHeadLeft.vue
  frontend/src/config/i18n/cn.js
  frontend/src/config/i18n/en.js
  frontend/src/mixins/tableHeader.js
  frontend/src/scss/common.scss
  frontend/src/views/admin/Space/DecisionTable/index.vue
  frontend/src/views/admin/Space/SpaceConfig/index.vue
  frontend/src/views/admin/Space/Task/index.vue
  frontend/src/views/admin/Space/Template/CreateTaskDialog.vue
  frontend/src/views/admin/Space/Template/CreateTemplateDialog.vue
  frontend/src/views/admin/Space/Template/index.vue
  frontend/src/views/admin/common/SpaceDialog.vue
  module_settings.py
  scripts/start_new_version.sh
  version_logs_md_en/V1.4.0_2024-01-24.md
  version_logs_md_en/V1.5.0_2024-02-22.md
  version_logs_md_en/V1.6.0_2024-03-27.md
  version_logs_md_en/V1.7.0_2024-06-06.md
  version_logs_md_en/V1.8.0_2024-08-01.md
Labels: feature

#52 feat: release V1.9.0 #31
  app_desc.yaml
  version_logs_md/V1.9.0_2024-10-29.md
  version_logs_md_en/V1.9.0_2024-10-29.md
Labels: feature
